### ISSUE TITLE
index modification

### ISSUE THREAD

**Issue by sebastianrosenzweig** [sebastianrosenzweig/mirdata#1]
The field "beat" for the multitracks points to a '.wav' file. I think it should point to the '.csv' file...

**Comment by helenacuesta** [comment]
@sebastianrosenzweig just did a commit of the updated script with this fix and some other minor things (https://github.com/sebastianrosenzweig/mirdata/commit/94a5db6bc9fadcdb0c061ac3b526bd27e8b7cb6d) plus the updated index file. I don't close the issue yet. Feel free to do so after checking it out.
